apiVersion: cnap.comcast.net/v1
kind: WebService
metadata:
  name: pbi-ui
  namespace: pfm-service
spec:
  servicePort: 8082
  regions:
    - wc
  autoscale:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 512m
      memory: 512Mi
  image: hub.comcast.net/pfm/pfm-ui:${VERSION}
  startupProbe:
    httpGet:
      path: /health
      port: 8082
    initialDelaySeconds: 90
  livenessProbe:
    httpGet:
      path: /health
      port: 8082
  serviceClaims:
    - name: pfm-vault
      service:
        provider: Vault
        path: kv2/comcast-pfm/devx/cnap/ui/${ENVIRONMENT}
      type: env
    - name: data-service
      service:
        kind: MongoDB
        name: pfm-db
      type: env
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: GIT_COMMIT
      value: ${GIT_COMMIT}
    - name: VERSION
      value: ${VERSION}
    - name: ENV
      value: ${ENVIRONMENT}