import { useLocalSearchParams, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text } from 'react-native';
import { apiFetch } from '@/api/client';
import type { Pool } from '@/api/types';
import { Screen } from '@/components/Screen';
import { colors } from '@/theme';
export default function PoolScreen(){const{id}=useLocalSearchParams<{id:string}>();const[pool,setPool]=useState<Pool|null>(null);const[error,setError]=useState('');useEffect(()=>{if(id)apiFetch<Pool>(`/pools/${encodeURIComponent(id)}`).then(setPool).catch(e=>setError(e.message));},[id]);if(error)return <Screen><Text style={styles.error}>{error}</Text></Screen>;if(!pool)return <Screen><ActivityIndicator color={colors.lime}/></Screen>;const webPath=pool.pool_type==='pickem'?`/pool/${id}/pickem`:pool.pool_type==='squares'?`/pool/${id}/squares`:`/pool/${id}/entries`;return <Screen><Text style={styles.type}>{pool.pool_type.toUpperCase()}</Text><Text style={styles.title}>{pool.name}</Text><Text style={styles.copy}>Native picking screens are next. Until then, continue securely in RunMyPool.</Text><Pressable style={styles.primary} onPress={()=>router.push({pathname:'/web',params:{path:webPath}})}><Text style={styles.primaryText}>Open picks</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.push({pathname:'/web',params:{path:`/pool/${id}/leaderboard`}})}><Text style={styles.secondaryText}>Leaderboard</Text></Pressable></Screen>}
const styles=StyleSheet.create({type:{color:colors.lime,fontWeight:'900',letterSpacing:2},title:{color:colors.text,fontSize:34,fontWeight:'900'},copy:{color:colors.muted,fontSize:16,lineHeight:23},primary:{backgroundColor:colors.lime,padding:15,borderRadius:12,alignItems:'center',marginTop:12},primaryText:{color:colors.ink,fontWeight:'900'},secondary:{borderColor:colors.cyan,borderWidth:1,padding:15,borderRadius:12,alignItems:'center'},secondaryText:{color:colors.cyan,fontWeight:'800'},error:{color:colors.danger}});
