import { router } from 'expo-router';
import { Pressable, StyleSheet, Text } from 'react-native';
import { useState } from 'react';
import { TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { Screen } from '@/components/Screen';
import { colors } from '@/theme';
export default function AccountScreen(){const{user,signOut,updateProfile}=useAuth();const[displayName,setDisplayName]=useState(user?.display_name||"");const[notice,setNotice]=useState("");const logout=async()=>{await signOut();router.replace('/login');};const save=async()=>{try{await updateProfile(displayName);setNotice("Display name saved.");}catch(error){setNotice((error as Error).message);}};return <Screen><Text style={styles.title}>Account</Text><Text style={styles.label}>Signed in as</Text><Text style={styles.email}>{user?.email}</Text><Text style={styles.label}>Display name</Text><TextInput accessibilityLabel="Display name" value={displayName} onChangeText={setDisplayName} maxLength={100} placeholder={user?.email.split("@")[0]} placeholderTextColor={colors.muted} style={styles.input}/><Pressable onPress={save} style={styles.button}><Text style={styles.email}>Save display name</Text></Pressable>{!!notice&&<Text style={styles.note}>{notice}</Text>}<Text style={styles.note}>Pool members will see this name instead of your email handle. Leave it blank to use your email handle.</Text><Pressable accessibilityRole="button" onPress={() => router.push("/privacy")} style={styles.button}><Text style={styles.email}>Privacy Policy</Text></Pressable><Pressable onPress={logout} style={styles.button}><Text style={styles.buttonText}>Sign out</Text></Pressable></Screen>}
const styles=StyleSheet.create({title:{color:colors.text,fontSize:32,fontWeight:'900'},label:{color:colors.muted,marginTop:12},email:{color:colors.text,fontSize:18,fontWeight:'800'},input:{color:colors.text,borderColor:colors.line,borderWidth:1,borderRadius:12,padding:12,marginTop:8},note:{color:colors.muted,lineHeight:22,backgroundColor:colors.panel,padding:16,borderRadius:14},button:{borderColor:colors.danger,borderWidth:1,borderRadius:12,padding:14,alignItems:'center',marginTop:20},buttonText:{color:colors.danger,fontWeight:'800'}});
